<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2012-2014  Stephan Kreutzer

This file is part of Freie Bibel.

Freie Bibel is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 or any later version,
as published by the Free Software Foundation.

Freie Bibel is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License 3 for more details.

You should have received a copy of the GNU Affero General Public License 3
along with Freie Bibel. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes" doctype-public="-//W3C//DTD XHTML 1.1//EN" doctype-system="http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"/>
  <xsl:template match="BIBLEBOOK">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <xsl:comment> This file was generated by hag2html.xsl of hag2epub2 (http://www.freie-bibel.de). </xsl:comment>
      <head profile="http://dublincore.org/documents/dcq-html/">
        <title>
          <xsl:choose>
            <xsl:when test="/BIBLEBOOK/CAPTION">
              <xsl:value-of select="/BIBLEBOOK/CAPTION"/>
            </xsl:when>
            <xsl:when test="/BIBLEBOOK/@bname">
              <xsl:value-of select="/BIBLEBOOK/@bname"/>
            </xsl:when>
            <xsl:when test="/BIBLEBOOK/@bsname">
              <xsl:value-of select="/BIBLEBOOK/@bsname"/>
            </xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="/BIBLEBOOK/@bnumber"/><xsl:text>. Buch</xsl:text>
            </xsl:otherwise>
          </xsl:choose>
        </title>

        <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/"/>

        <meta name="DC.generator" content="hag2html.xsl of hag2epub2 (http://www.freie-bibel.de)"/>
        <meta name="DC.type" content="Text"/>
        <meta name="DC.format" content="application/xhtml+xml"/>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
      </head>
      <body>
        <div id="id_{./@bnumber}">
          <xsl:choose>
            <xsl:when test="./CAPTION">
              <h2><xsl:value-of select="./CAPTION"/></h2>
            </xsl:when>
            <xsl:when test="./@bname">
              <h2><xsl:value-of select="./@bname"/></h2>
            </xsl:when>
            <xsl:when test="./@bsname">
              <h2><xsl:value-of select="./@bsname"/></h2>
            </xsl:when>
            <xsl:otherwise>
              <h2><xsl:value-of select="./@bnumber"/><xsl:text>. Buch</xsl:text></h2>
            </xsl:otherwise>
          </xsl:choose>
          <div id="id_kapiteluebersicht">
            <p style="text-align:center;">
              <a href="information.xhtml#id_buchuebersicht">Buchübersicht</a>
            </p>
            <hr/>
            Kapitel:
            <xsl:for-each select="./CHAPTER">
              <a href="#id_{../@bnumber}_{./@cnumber}"><xsl:value-of select="./@cnumber"/></a><xsl:text>&#x20;</xsl:text>
            </xsl:for-each>
            <hr/>
          </div>
          <xsl:apply-templates select="CHAPTER"/>
          <div id="id_footnotes">
            <h2>Fußnoten</h2>
            <xsl:for-each select="./CHAPTER">
              <div id="id_footnotes_{./@cnumber}">
                <h3>Kapitel <xsl:value-of select="./@cnumber"/></h3>
                <p style="text-align:justify;">
                  <xsl:for-each select="./PARAGRAPH/VERSE/NOTE | ./VERSE/NOTE">
                    <xsl:choose>
                      <xsl:when test="../../../@cnumber">
                        <a><xsl:attribute name="id"><xsl:text>footnote_</xsl:text><xsl:value-of select="../../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER//VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute>[</a>
                        <a><xsl:attribute name="href"><xsl:text>#footnotemark_</xsl:text><xsl:value-of select="../../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER//VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute><xsl:number count="//CHAPTER//VERSE/NOTE" level="any" from="//CHAPTER"/></a>]
                      </xsl:when>
                      <xsl:when test="../../@cnumber">
                        <a><xsl:attribute name="id"><xsl:text>footnote_</xsl:text><xsl:value-of select="../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER/VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute>[</a>
                        <a><xsl:attribute name="href"><xsl:text>#footnotemark_</xsl:text><xsl:value-of select="../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER/VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute><xsl:number count="//CHAPTER/VERSE/NOTE" level="any" from="//CHAPTER"/></a>]
                      </xsl:when>
                    </xsl:choose>
                    <xsl:value-of select="."/><xsl:text>&#xA;</xsl:text>
                  </xsl:for-each>
                </p>
              </div>
            </xsl:for-each>
            <div style="text-align:center;">
              <a href="#id_kapiteluebersicht">Kapitelübersicht</a><br/>
              <a href="information.xhtml#id_buchuebersicht">Buchübersicht</a>
            </div>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
  <xsl:template match="CHAPTER">
    <div id="id_{../@bnumber}_{./@cnumber}">
      <h3><xsl:text>Kapitel&#x20;</xsl:text><xsl:value-of select="@cnumber"/></h3>
      <div>
        <xsl:apply-templates select="VERSE | PARAGRAPH"/>
      </div>
      <div style="text-align:center;">
        <a href="#id_kapiteluebersicht">Kapitelübersicht</a>
      </div>
    </div>
  </xsl:template>
  <xsl:template match="PARAGRAPH">
    <p style="text-align:justify;">
      <xsl:apply-templates select="VERSE"/>
    </p>
  </xsl:template>
  <xsl:template match="VERSE">
    <span style="color:gray;"><xsl:value-of select="@vnumber"/></span><xsl:text>&#x20;</xsl:text>
    <xsl:apply-templates/>
    <xsl:text>&#x20;</xsl:text>
  </xsl:template>
  <xsl:template match="VERSE//text()">
    <xsl:value-of select="."/>
  </xsl:template>
  <xsl:template match="STYLE">
    <xsl:choose>
      <xsl:when test="@fs='super'">
        <span style="font-size:0.7em"><xsl:value-of select="."/></span>
      </xsl:when>
      <xsl:when test="@fs='emphasis'">
        <b><xsl:value-of select="."/></b>
      </xsl:when>
      <xsl:when test="@fs='italic'">
        <i><xsl:value-of select="."/></i>
      </xsl:when>
    </xsl:choose>
  </xsl:template>
  <xsl:template match="NOTE">
    <xsl:choose>
      <xsl:when test="../../../@cnumber"><a><xsl:attribute name="id"><xsl:text>footnotemark_</xsl:text><xsl:value-of select="../../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER//VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute>[</a><a><xsl:attribute name="href"><xsl:text>#footnote_</xsl:text><xsl:value-of select="../../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER//VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute><xsl:number count="//CHAPTER//VERSE/NOTE" level="any" from="//CHAPTER"/></a>]</xsl:when>
      <xsl:when test="../../@cnumber"><a><xsl:attribute name="id"><xsl:text>footnotemark_</xsl:text><xsl:value-of select="../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER/VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute>[</a><a><xsl:attribute name="href"><xsl:text>#footnote_</xsl:text><xsl:value-of select="../../@cnumber"/><xsl:text>_</xsl:text><xsl:number count="//CHAPTER/VERSE/NOTE" level="any" from="//CHAPTER"/></xsl:attribute><xsl:number count="//CHAPTER/VERSE/NOTE" level="any" from="//CHAPTER"/></a>]</xsl:when>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
