<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2012-2013  Stephan Kreutzer

This file is part of Freie Bibel.

Freie Bibel is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 or any later version,
as published by the Free Software Foundation.

Freie Bibel is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License 3 for more details.

You should have received a copy of the GNU Affero General Public License 3
along with Freie Bibel. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="XMLBIBLE">
    <xsl:comment> This file was generated by hag2opf.xsl of hag2epub2 (http://www.freie-bibel.de). </xsl:comment>
    <package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf" xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="BookId">
      <metadata>
        <dc:title><xsl:value-of select="/XMLBIBLE/INFORMATION/title"/></dc:title>
        <xsl:comment> Original creator is replaced by publisher to display the official publishing entity of the bible module. </xsl:comment>
        <dc:creator><xsl:value-of select="/XMLBIBLE/INFORMATION/publisher"/></dc:creator>
        <dc:description><xsl:value-of select="/XMLBIBLE/INFORMATION/description"/></dc:description>
        <dc:publisher><xsl:value-of select="/XMLBIBLE/INFORMATION/publisher"/></dc:publisher>
        <dc:subject><xsl:value-of select="/XMLBIBLE/INFORMATION/subject"/></dc:subject>
        <xsl:for-each select="/XMLBIBLE/INFORMATION/contributor">
          <dc:contributor><xsl:value-of select="."/></dc:contributor>
        </xsl:for-each>
        <xsl:comment> Original creator of the bible module added to the list of contributors. </xsl:comment>
        <dc:contributor><xsl:value-of select="/XMLBIBLE/INFORMATION/creator"/></dc:contributor>
        <dc:date><xsl:value-of select="/XMLBIBLE/INFORMATION/date"/></dc:date>
        <dc:identifier id="BookId"><xsl:value-of select="/XMLBIBLE/INFORMATION/identifier"/></dc:identifier>
        <dc:source><xsl:value-of select="/XMLBIBLE/INFORMATION/source"/></dc:source>
        <dc:language xsi:type="dcterms:RFC3066"><xsl:value-of select="/XMLBIBLE/INFORMATION/language"/></dc:language>
        <dc:coverage><xsl:value-of select="/XMLBIBLE/INFORMATION/coverage"/></dc:coverage>
        <dc:rights><xsl:value-of select="/XMLBIBLE/INFORMATION/rights"/></dc:rights>
      </metadata>
      <manifest>
        <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
        <item id="id_information" href="information.xhtml" media-type="application/xhtml+xml"/>
        <xsl:for-each select="/XMLBIBLE/BIBLEBOOK">
          <item id="id_{./@bnumber}" href="{./@bnumber}.xhtml" media-type="application/xhtml+xml"/>
        </xsl:for-each>
      </manifest>
      <spine toc="ncx">
        <itemref idref="id_information"/>
        <xsl:for-each select="/XMLBIBLE/BIBLEBOOK">
          <itemref idref="id_{./@bnumber}"/>
        </xsl:for-each>
      </spine>
    </package>
  </xsl:template>
</xsl:stylesheet>
