<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2012-2013  Stephan Kreutzer

This file is part of Freie Bibel.

Freie Bibel is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 or any later version,
as published by the Free Software Foundation.

Freie Bibel is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License 3 for more details.

You should have received a copy of the GNU General Public License
along with Freie Bibel. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="XMLBIBLE">
    <xsl:comment> This file was generated by hag2navtoc.xsl of hag2epub3 (http://www.freie-bibel.de). </xsl:comment>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
      <head>
        <meta charset="utf-8"/>
      </head>
      <body>
        <nav epub:type="toc" id="toc">
          <ol>
            <li>
              <a href="information.xhtml">Information</a>
            </li>
            <xsl:apply-templates select="BIBLEBOOK"/>
          </ol>
        </nav>
      </body>
    </html>
  </xsl:template>
  <xsl:template match="BIBLEBOOK">
    <li>
      <a href="{./@bnumber}.xhtml">
      <xsl:choose>
        <xsl:when test="./CAPTION">
          <xsl:value-of select="./CAPTION"/>
        </xsl:when>
        <xsl:when test="./@bname">
          <xsl:value-of select="./@bname"/>
        </xsl:when>
        <xsl:when test="./@bsname">
          <xsl:value-of select="./@bsname"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="./@bnumber"/><xsl:text>. Buch</xsl:text>
        </xsl:otherwise>
      </xsl:choose>
      </a>
    </li>
  </xsl:template>
</xsl:stylesheet>
