<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2012-2013  Stephan Kreutzer, Claas-Fridjof Lisowski

This file is part of Freie Bibel.

Freie Bibel is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 or any later version,
as published by the Free Software Foundation.

Freie Bibel is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License 3 for more details.

You should have received a copy of the GNU General Public License
along with Freie Bibel. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="BIBLEBOOK">
    <xsl:text disable-output-escaping='yes'>&lt;!DOCTYPE html>&#xA;</xsl:text>
    <xsl:comment> This file was generated by hag2html.xsl of hag2epub3 (http://www.freie-bibel.de). </xsl:comment>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
      <head>
        <title>
          <xsl:choose>
            <xsl:when test="/BIBLEBOOK/CAPTION">
              <xsl:value-of select="/BIBLEBOOK/CAPTION"/>
            </xsl:when>
            <xsl:when test="/BIBLEBOOK/@bname">
              <xsl:value-of select="/BIBLEBOOK/@bname"/>
            </xsl:when>
            <xsl:when test="/BIBLEBOOK/@bsname">
              <xsl:value-of select="/BIBLEBOOK/@bsname"/>
            </xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="/BIBLEBOOK/@bnumber"/><xsl:text>. Buch</xsl:text>
            </xsl:otherwise>
          </xsl:choose>
        </title>

        <link href="epub1style.css" rel="stylesheet" type="text/css"/>
        <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/"/>

        <meta name="DC.generator" content="hag2html.xsl of hag2epub3 (http://www.freie-bibel.de)"/>
        <meta name="DC.type" content="Text"/>
        <meta name="DC.format" content="application/xhtml+xml"/>
      </head>
      <body>
        <div id="id_{/BIBLEBOOK/@bnumber}">
          <xsl:choose>
            <xsl:when test="/BIBLEBOOK/CAPTION">
              <h1><xsl:value-of select="/BIBLEBOOK/CAPTION"/></h1>
            </xsl:when>
            <xsl:when test="/BIBLEBOOK/@bname">
              <h1><xsl:value-of select="/BIBLEBOOK/@bname"/></h1>
            </xsl:when>
            <xsl:when test="/BIBLEBOOK/@bsname">
              <h1><xsl:value-of select="/BIBLEBOOK/@bsname"/></h1>
            </xsl:when>
            <xsl:otherwise>
              <h1><xsl:value-of select="/BIBLEBOOK/@bnumber"/><xsl:text>. Buch</xsl:text></h1>
            </xsl:otherwise>
          </xsl:choose>
          <hr/>
          Kapitel:
          <xsl:for-each select="/BIBLEBOOK/CHAPTER">
            <a href="#id_{../@bnumber}_{./@cnumber}"><xsl:value-of select="./@cnumber"/></a><xsl:text>&#x20;</xsl:text>
          </xsl:for-each>
          <hr/>
          <xsl:apply-templates select="CHAPTER"/>
        </div>
      </body>
    </html>
  </xsl:template>
  <xsl:template match="CHAPTER">
    <div id="id_{../@bnumber}_{./@cnumber}">
      <h2><xsl:text>Kapitel&#x20;</xsl:text><xsl:value-of select="@cnumber"/></h2>
      <div>
        <xsl:apply-templates select="VERSE | PARAGRAPH"/>
      </div>
    </div>
    <div>
      <xsl:for-each select="descendant::NOTE">
        <aside epub:type="footnote">
          <xsl:attribute name="id"><xsl:text>footnote_</xsl:text><xsl:number count="*[self::NOTE]" level="any"/></xsl:attribute>
          <xsl:value-of select="."/>
        </aside>
      </xsl:for-each>
    </div>
  </xsl:template>
  <xsl:template match="PARAGRAPH">
    <p>
      <xsl:apply-templates select="VERSE"/>
    </p>
  </xsl:template>
  <xsl:template match="VERSE">
    <sup>
      <xsl:value-of select="@vnumber"/>
    </sup>
    <xsl:apply-templates/>
    <xsl:text>&#x20;</xsl:text>
  </xsl:template>
  <xsl:template match="VERSE//text()">
    <xsl:value-of select="."/>
  </xsl:template>
  <xsl:template match="STYLE">
    <xsl:choose>
      <xsl:when test="@fs='super'">
        <span class="vsuper"><xsl:value-of select="."/></span>
      </xsl:when>
      <xsl:when test="@fs='emphasis'">
        <b><xsl:value-of select="."/></b>
      </xsl:when>
      <xsl:when test="@fs='italic'">
        <i><xsl:value-of select="."/></i>
      </xsl:when>
    </xsl:choose>
  </xsl:template>
  <xsl:template match="NOTE">
    <a epub:type="noteref" class="note">
      <xsl:attribute name="href"><xsl:text>#footnote_</xsl:text><xsl:number count="*[self::NOTE]" level="any"/></xsl:attribute>
      <xsl:text>*</xsl:text>
    </a>
  </xsl:template>
</xsl:stylesheet>
