<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2012-2013  Stephan Kreutzer

This file is part of Freie Bibel.

Freie Bibel is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 or any later version,
as published by the Free Software Foundation.

Freie Bibel is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License 3 for more details.

You should have received a copy of the GNU General Public License
along with Freie Bibel. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes" doctype-public="-//NISO//DTD ncx 2005-1//EN" doctype-system="http://www.daisy.org/z3986/2005/ncx-2005-1.dtd"/>
  <xsl:template match="XMLBIBLE">
    <xsl:comment> This file was generated by hag2ncx.xsl of hag2epub (http://www.freie-bibel.de). </xsl:comment>
    <ncx xmlns:ncx="http://www.daisy.org/z3986/2005/ncx/" version="2005-1" xml:lang="{/XMLBIBLE/INFORMATION/language}">
      <head>
        <meta name="dc:Title" content="{/XMLBIBLE/INFORMATION/title}"/>
        <meta name="dtb:uid" content="{/XMLBIBLE/INFORMATION/identifier}"/>
      </head>
      <docTitle>
        <text><xsl:value-of select="/XMLBIBLE/INFORMATION/title"/></text>
      </docTitle>
      <navMap>
        <xsl:apply-templates select="INFORMATION"/>
        <xsl:apply-templates select="BIBLEBOOK"/>
      </navMap>
    </ncx>
  </xsl:template>
  <xsl:template match="INFORMATION">
    <navPoint id="metadata_information">
      <xsl:attribute name="playOrder"><xsl:number count="*[self::BIBLEBOOK or self::CHAPTER or self::INFORMATION]" level="any"/></xsl:attribute>
        <navLabel>
          <text>Information</text>
        </navLabel>
      <content src="bible.xhtml#metadata_information"/>
    </navPoint>
  </xsl:template>
  <xsl:template match="BIBLEBOOK">
    <navPoint id="id_{./@bnumber}" >
      <xsl:attribute name="playOrder"><xsl:number count="*[self::BIBLEBOOK or self::CHAPTER or self::INFORMATION]" level="any"/></xsl:attribute>
      <navLabel>
        <text>
          <xsl:choose>
            <xsl:when test="./@bname">
              <xsl:value-of select="./@bname"/>
            </xsl:when>
            <xsl:when test="./@bsname">
              <xsl:value-of select="./@bsname"/>
            </xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="./@bnumber"/><xsl:text>. Buch</xsl:text>
            </xsl:otherwise>
          </xsl:choose>
        </text>
      </navLabel>
      <content src="bible.xhtml#id_{./@bnumber}"/>
      <xsl:apply-templates select="CHAPTER"/>
    </navPoint>
  </xsl:template>
  <xsl:template match="CHAPTER">
    <navPoint id="id_{../@bnumber}_{./@cnumber}">
      <xsl:attribute name="playOrder"><xsl:number count="*[self::BIBLEBOOK or self::CHAPTER or self::INFORMATION]" level="any"/></xsl:attribute>
      <navLabel>
        <text>Kapitel <xsl:value-of select="./@cnumber"/></text>
      </navLabel>
      <content src="bible.xhtml#id_{../@bnumber}_{./@cnumber}"/>
    </navPoint>
  </xsl:template>
</xsl:stylesheet>
